# Application Server Port
server:
  port: 8688

# DataSource Config

# Custom Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbname?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: username
    password: password
  jpa:
    show-sql: true

user: SixAwn
password: 123456