server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:port/dbname?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: username
    password: password
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: 1ms


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fitt.sixawn.entity
  global-config:
    banner: false

jodconverter:
  local:
    enabled: true
    office-home: /Applications/LibreOffice.app/Contents
    port-number: 8102
    max-task-per-process: 100
  store:
    path: filepath

logging:
  level:
    com.microsoft.sqlserver.jdbc: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG
    com.fitt.sixawn: DEBUG
  pattern:
    console: " %red(%d{yyyy-MM-dd HH:mm:ss}) %boldGreen([%thread]) %highlight([%level]) %cyan(%logger) - %magenta(%msg%n)"
