server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /userInfo

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.50.40:1433;DatabaseName=MDT
    username: sa
    password: sa
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fitt.sixawn.entity

logging:
  level:
    cc.hidoctor: DEBUG
    com.microsoft.sqlserver.jdbc: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG
  pattern:
    console: "%boldMagenta(%d{yyyy-MM-dd HH:mm:ss}) [%p] %highlight(%C:%L) : %m %n"
