server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /userInfo

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:port/daname?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: username
    password: password

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fitt.sixawn.entity

jodconverter:
  local:
    enabled: true
    office-home: /Applications/LibreOffice.app/Contents
    port-number: 8100,8101,8102
    max-task-per-process: 100
  store:
    path: /data/file

logging:
  level:
    com.microsoft.sqlserver.jdbc: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG
  pattern:
    console: "%boldMagenta(%d{yyyy-MM-dd HH:mm:ss}) [%p] %highlight(%C:%L) : %m %n"
