server:
  port: 8081

logging:
  level:
    cc.hidoctor: DEBUG
    com.microsoft.sqlserver.jdbc: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG
  pattern:
    console: "%boldMagenta(%d{yyyy-MM-dd HH:mm:ss}) [%p] %highlight(%C:%L) : %m %n"

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://222.240.240.215:3306/2019ncov?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: 2019ncov
    password: 2019ncov
    filters: stat
    maxActive: 10
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fitt.sixawn.entity

